name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter
          curl -sSL https://install.python-poetry.org | python3 - --version 1.2.2

      - name: Setup template
        run: |
          export PATH="${PATH}:/root/.local/bin/"
          ./test/create.sh

      - name: Test template
        run: |
          export PATH="${PATH}:/root/.local/bin/"
          ./test/test.sh

      - name: Run template
        run: |
          export PATH="${PATH}:/root/.local/bin/"
          ./test/prepare.sh
          ./test/run.sh
